### ISSUE TITLE
Lost top buttons and icon in 2.4 beta 4

### ISSUE THREAD

**Issue by cocos56** [rejetto/hfs2#3]
Using IPv6 access :
![image](https://user-images.githubusercontent.com/36597804/82872669-ef170d00-9f65-11ea-9063-5a73fd86fdb6.png)
Using IPv4 access :
![image](https://user-images.githubusercontent.com/36597804/82872693-f76f4800-9f65-11ea-8a56-fd7758e9b756.png)

**Comment by rejetto** [comment]
I cannot reproduce the problem. Suggestions?
Try to gather more infos yourself, have a look in the network panel of the browser to see what's happening, or in HFS' log.

**Comment by cocos56** [comment]
The problem has been solved in 2.4 beta 7.

**Comment by cocos56** [comment]
But a new problem has arisen, it is not accessible through the IP address of part of the virtual networks.
![image](https://user-images.githubusercontent.com/36597804/83257237-868a9300-a1e6-11ea-97cb-dd29b70b9512.png)
![image](https://user-images.githubusercontent.com/36597804/83257431-f6008280-a1e6-11ea-9fa0-dad8ead07634.png)

**Comment by cocos56** [comment]
Cannot be accessed by itself, but can be accessed by other computers.
![image](https://user-images.githubusercontent.com/36597804/83257513-1f211300-a1e7-11ea-96d7-1ed7d6ab8b07.png)

**Comment by cocos56** [comment]
https://my.zerotier.com/

ZeroTier Central provides a friendly web UI and API for managing ZeroTier network controllers as well as related services that can be added to networks.

**Comment by cocos56** [comment]
The problem appears on some browsers, QQ browser reappears, and Edge browser does not reproduce.

![image](https://user-images.githubusercontent.com/36597804/83257843-c605af00-a1e7-11ea-9746-0b4c7b6c1601.png)
![image](https://user-images.githubusercontent.com/36597804/83257921-e9c8f500-a1e7-11ea-8868-7c3383a237bf.png)

**Comment by rejetto** [comment]
so, it's nothing related to hfs it seems

**Comment by NaitLee** [comment]
Oh, finally found another victim of dual-core browsers :)

360 Browser, QQ Browser will use IE core by default for IP-address-accessing sites, that's why the "ipv6" (see address bar, there's a domain name) and "ipv4" (see address bar again, an IP) not same.

HFS 2.4 default template control panel is inited with javascript (jquery). IE cannot understand modern js syntax.

You can switch core by clicking that 'e' or thunder sign on the right of address bar.

Or better, **不要用所谓的双核浏览器了，它们就会骗人。**

So, it's just the old-to-die Internet Explorer caused this problem. Never mind. :)
